### ISSUE TITLE
java -jar swapper but Visit this url http://localhost:8000 or http://localhost:8080 , is error.

### ISSUE THREAD

**Issue by huangkaiyan10** [sunwu51/JVMByteSwapTool#33]
but Visit this url http://localhost:8000 or http://localhost:8080 , is error.

_Originally posted by @huangkaiyan10 in https://github.com/sunwu51/JVMByteSwapTool/issues/32#issuecomment-2316969341_

**Comment by huangkaiyan10** [comment]
![image](https://github.com/user-attachments/assets/cb2ca249-0653-4d1a-ae9d-a544aad9ce80)

**Comment by huangkaiyan10** [comment]
![image](https://github.com/user-attachments/assets/36e52109-2ea5-44af-a234-74b19ee6e71b)

**Comment by huangkaiyan10** [comment]
can I config  custom port , not use 8000?

**Comment by huangkaiyan10** [comment]
mycomputer may be controlled by the organization and I cannot use port 8000

**Comment by sunwu51** [comment]
Not yet supported, hard code now. https://github.com/sunwu51/JVMByteSwapTool/blob/master/src/main/java/w/App.java#L21

But it's a good suggestion, will add a param config when attaching.

**Comment by sunwu51** [comment]
Hi, now in v0.0.7, you can pass a specific port in the param:
```bash
$ java -jar -Dw_http_port=<your prefer port> swapper.jar
```
